uploads = []
outputs = []

[[generated]]
id = "muZ-PIZKh6n3dAr72RMsS"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "veloura app icon"

[[generated]]
id = "F5eetRq5iramUz76sMe-5"
uri = "file://artifacts/mobile/assets/images/aura-avatar.png"
type = "image"
title = "aura AI stylist avatar"
